const dataFicheConsultant = [
  {
    id: 1,
    label: "Prénom",
    type: "text",
    name: "firstname",
    placeholder: "Josephine",
    value: "",
    className: "form_input_consultant",
  },
  {
    id: 2,
    label: "Nom",
    type: "text",
    name: "lastname",
    placeholder: "Baker",
    value: "",
    className: "form_input_consultant",
  },
  {
    id: 3,
    label: "Ville",
    type: "text",
    name: "city",
    placeholder: "Bordeaux",
    value: "",
    className: "form_input_consultant",
  },
  {
    id: 4,
    label: "LinkedIn",
    type: "text",
    name: "linkedin",
    placeholder: "https://www.linkedin.com/in/josephine-backer/",
    value: "",
    className: "form_input_consultant",
  },
  {
    id: 5,
    label: "Téléphone",
    type: "text",
    name: "phone",
    placeholder: "07 89 56 45 87",
    value: "",
    className: "form_input_consultant",
  },
  {
    id: 6,
    label: "Email",
    type: "email",
    name: "email",
    placeholder: "josephine.baker@gmail.com",
    value: "",
    className: "form_input_consultant",
  },
  {
    id: 7,
    label: "Mot de passe",
    type: "text",
    name: "password",
    placeholder: "test1234",
    value: "",
    className: "form_input_consultant",
  },
];
export default dataFicheConsultant;
