const firmForm = [
  {
    id: 1,
    label: "Nom de l'entreprise",
    type: "text",
    name: "name",
    placeholder: "",
    value: "",
    className: "firmform-subtitle",
  },
  {
    id: 2,
    label: "Id du consultant",
    type: "number",
    name: "consultant_id",
    placeholder: "",
    value: "",
    className: "firmform-subtitle",
  },
  {
    id: 3,
    label: "Logo de l'entreprise",
    type: "text",
    name: "logo_url",
    placeholder: "lien http du logo",
    value: "",
    className: "firmform-subtitle",
  },

  {
    id: 4,
    label: "Email de l'entreprise",
    type: "email",
    name: "email",
    placeholder: "",
    value: "",
    className: "firmform-subtitle",
  },

  {
    id: 5,
    label: "Numéro de téléphone de l'entreprise",
    type: "text",
    name: "contact_phone",
    placeholder: "",
    value: "",
    className: "firmform-subtitle",
  },
  {
    id: 6,
    label: "Adresse de l'entreprise",
    name: "adress",
    placeholder: "",
    value: "",
    className: "firmform-subtitle",
  },
  {
    id: 7,
    label: "Ville de l'entreprise",
    type: "text",
    name: "city",
    placeholder: "",
    value: "",
    className: "firmform-subtitle",
  },
  {
    id: 8,
    label: "Code postal de l'entreprise",
    type: "number",
    name: "postal_code",
    placeholder: "",
    value: "",
    className: "firmform-subtitle",
  },

  {
    id: 9,
    label: "Pays de l'entreprise",
    type: "text",
    name: "country",
    placeholder: "",
    value: "",
    className: "firmform-subtitle",
  },
];

export default firmForm;
